/** \mainpage Driver Overview
  *
  * \section section_drv_info Driver Information
  * This Sensor Controller Interface driver has been generated by the Texas Instruments Sensor Controller
  * Studio tool:
  * - <b>Project name</b>:     twochannel
  * - <b>Project file</b>:     E:/twoChannel/twochannel_1.scp
  * - <b>Code prefix</b>:      -
  * - <b>Operating system</b>: None
  * - <b>Tool version</b>:     1.4.1.54
  * - <b>Tool patches</b>:     None
  * - <b>Target chip</b>:      CC2650, revision -, package QFN48 7x7 RGZ
  * - <b>Created</b>:          2017-05-24 05:02:38.444
  * - <b>Computer</b>:         WINDEV1612EVAL
  * - <b>User</b>:             User
  *
  * No user-provided resource definitions were used to generate this driver.
  *
  * No user-provided procedure definitions were used to generate this driver.
  *
  * Do not edit the generated source code files other than temporarily for debug purposes. Any
  * modifications will be overwritten by the Sensor Controller Studio when generating new output.
  *
  * \section section_drv_modules Driver Modules
  * The driver is divided into three modules:
  * - \ref module_scif_generic_interface, providing the API for:
  *     - Initializing and uninitializing the driver
  *     - Task control (for starting, stopping and executing Sensor Controller tasks)
  *     - Task data exchange (for producing input data to and consume output data from Sensor Controller
  *       tasks)
  * - \ref module_scif_driver_setup, containing:
  *     - The AUX RAM image (Sensor Controller code and data)
  *     - I/O mapping information
  *     - Task data structure information
  *     - Driver setup data, to be used in the driver initialization
  *     - Project-specific functionality
  * - \ref module_scif_osal, for flexible OS support:
  *     - Interfaces with the selected operating system
  *
  * It is possible to use output from multiple Sensor Controller Studio projects in one application. Only
  * one driver setup may be active at a time, but it is possible to switch between these setups. When
  * using this option, there is one instance of the \ref module_scif_generic_interface and
  * \ref module_scif_osal modules, and multiple instances of the \ref module_scif_driver_setup module.
  * This requires that:
  * - The outputs must be generated using the same version of Sensor Controller Studio
  * - The outputs must use the same operating system
  * - The outputs must use different source code prefixes (inserted into all globals of the
  *   \ref module_scif_driver_setup)
  *
  *
  * \section section_project_info Project Description
  * No description entered
  *
  *
  * \subsection section_io_mapping I/O Mapping
  * Task I/O functions are mapped to the following pins:
  * - New task:
  *     - <b>A: Channel 2</b>: DIO27
  *     - <b>A: Channel 1</b>: DIO24
  *     - <b>O: drain channel 1</b>: DIO25
  *     - <b>O: Drain channel 2</b>: DIO23
  *
  *
  * \section section_task_info Task Description(s)
  * This driver supports the following task(s):
  *
  *
  * \subsection section_task_desc_new_task New task
  * No description entered
  *
  */




/** \addtogroup module_scif_driver_setup Driver Setup
  *
  * \section section_driver_setup_overview Overview
  *
  * This driver setup instance has been generated for:
  * - <b>Project name</b>:     twochannel
  * - <b>Code prefix</b>:      -
  *
  * The driver setup module contains the generated output from the Sensor Controller Studio project:
  * - Location of task control and scheduling data structures in AUX RAM
  * - The AUX RAM image, and the size the image
  * - Task data structure information (location, size and buffer count)
  * - I/O pin mapping translation table
  * - Task resource initialization and uninitialization functions
  *
  * @{
  */
#ifndef SCIF_H
#define SCIF_H

#include <stdint.h>
#include <stdbool.h>
#include "scif_framework.h"
#include "scif_osal_none.h"


/// Target chip name
#define SCIF_TARGET_CHIP_NAME_CC2650
/// Target chip package
#define SCIF_TARGET_CHIP_PACKAGE_QFN48_7X7_RGZ

/// Number of tasks implemented by this driver
#define SCIF_TASK_COUNT 1

/// New task: Task ID
#define SCIF_NEW_TASK_TASK_ID 0


/// New task I/O mapping: Channel 2
#define SCIF_NEW_TASK_DIO_A_CH2 27
/// New task I/O mapping: Channel 1
#define SCIF_NEW_TASK_DIO_A_CH1 24
/// New task I/O mapping: drain channel 1
#define SCIF_NEW_TASK_DIO_O_DRAINCH1 25
/// New task I/O mapping: Drain channel 2
#define SCIF_NEW_TASK_DIO_O_DRAINCH2 23


// All shared data structures in AUX RAM need to be packed
#pragma pack(push, 2)


/// New task: Task configuration structure
typedef struct {
    uint16_t dlevel;     ///< 
    uint16_t dlevelreed; ///< 
    uint16_t namurHigh;  ///< 
    uint16_t namurLevel; ///< 
    uint16_t namurLow;   ///< 
    uint16_t pollTime;   ///< Time between polls
    uint16_t reedLevel;  ///< 
} SCIF_NEW_TASK_CFG_T;


/// New task: Task output data structure
typedef struct {
    uint16_t adcValueCh1;     ///< 
    uint16_t adcValueCh2;     ///< 
    uint16_t channelErrorCh1; ///< 
    uint16_t channelErrorCh2; ///< 
    uint16_t counterNamurCh1; ///< 
    uint16_t counterNamurCh2; ///< 
    uint16_t counterReedCh1;  ///< 
    uint16_t counterReedCh2;  ///< 
    uint16_t dummy;           ///< 0
    uint16_t typeCh1;         ///< 
    uint16_t typeCh2;         ///< 
} SCIF_NEW_TASK_OUTPUT_T;


/// New task: Task state structure
typedef struct {
    uint16_t buttonStateCh1;      ///< 
    uint16_t buttonStateCh2;      ///< 
    uint16_t clearCounterCh1;     ///< 
    uint16_t clearCounterCh2;     ///< 
    uint16_t clearErrorCh1;       ///< 
    uint16_t clearErrorCh2;       ///< 
    uint16_t currTriggerLevelCh1; ///< 
    uint16_t currTriggerLevelCh2; ///< 
    uint16_t derrorch1;           ///< 
    uint16_t derrorch2;           ///< 
    uint16_t inDebounceCh1;       ///< 
    uint16_t inDebounceCh2;       ///< 
    uint16_t loopcounter;         ///< 
    uint16_t numpoll1;            ///< 
    uint16_t numpoll2;            ///< 
} SCIF_NEW_TASK_STATE_T;


/// Sensor Controller task data (configuration, input buffer(s), output buffer(s) and internal state)
typedef struct {
    struct {
        SCIF_NEW_TASK_CFG_T cfg;
        SCIF_NEW_TASK_OUTPUT_T output;
        SCIF_NEW_TASK_STATE_T state;
    } newTask;
} SCIF_TASK_DATA_T;

/// Sensor Controller task generic control (located in AUX RAM)
#define scifTaskData    (*((volatile SCIF_TASK_DATA_T*) 0x400E00E8))


// Initialized internal driver data, to be used in the call to \ref scifInit()
extern const SCIF_DATA_T scifDriverSetup;


// Restore previous struct packing setting
#pragma pack(pop)


// AUX I/O re-initialization functions
void scifReinitTaskIo(uint32_t bvTaskIds);


// No task-specific API available


#endif
//@}


// Generated by WINDEV1612EVAL at 2017-05-24 05:02:38.444
